import {readFile,writeFile,mkdir,cp,rm} from 'node:fs/promises';
const profile=JSON.parse(await readFile(new URL('../content/profile.json',import.meta.url),'utf8'));
const projects=JSON.parse(await readFile(new URL('../content/projects.json',import.meta.url),'utf8'));
const root=new URL('../dist/',import.meta.url); await rm(root,{recursive:true,force:true});await mkdir(root,{recursive:true});await cp(new URL('../site/assets',import.meta.url),new URL('assets/',root),{recursive:true});
const e=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const client=p=>profile.anonymous?p.alias:p.client;
const featured=projects.filter(p=>p.featured);
const supporting=projects.filter(p=>!p.featured);
const link=(p)=>`projects/${p.id}.html`;
function layout(title,body,active='Home',depth=0){let b=depth?'../':'./';return `<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="박상연의 마케팅 포트폴리오. 광고 운영, GA4/GTM 분석, 전환 측정과 시장조사 사례."><meta name="theme-color" content="#f7f8fa"><title>${e(title)} · ${e(profile.englishName)}</title><link rel="icon" href="${b}assets/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="${b}assets/style.css"><script src="${b}assets/main.js" defer></script></head><body><a class="skip" href="#main">본문으로 건너뛰기</a><header class="header"><a class="brand" href="${b}index.html" aria-label="박상연 포트폴리오 홈"><span class="brand-icon">S.</span>${e(profile.englishName)}<span class="brand-role"> / MARKETING</span></a><nav aria-label="주 메뉴">${[['Home','index.html'],['About','about.html'],['Projects','projects.html'],['Resume','resume.html']].map(([n,h])=>`<a href="${b}${h}" ${active===n?'aria-current="page"':''}>${n}${n==='Resume'?' <span aria-hidden="true">↗</span>':''}</a>`).join('')}</nav></header><main id="main">${body}</main><footer><a class="brand" href="${b}index.html">${e(profile.englishName)}</a><span>Measure thoughtfully. Improve deliberately.</span><span>PORTFOLIO / ${e(profile.updated)}</span></footer></body></html>`}
const tags=p=>`<div class="tags">${p.tags.map(t=>`<span>${e(t)}</span>`).join('')}</div>`;

const labels={'Overview':'프로젝트 개요','Problem':'문제','Goal':'목표','My Role':'내 역할','Analysis':'분석 근거','Action':'실행과 제안','Result':'결과와 한계','Insight':'배운 점'};
const anchor=k=>k.toLowerCase().replaceAll(' ','-');
const contact=`<a href="mailto:${e(profile.email)}">${e(profile.email)}</a>`;
function career(list){return list.map(x=>`<article class="career-entry"><div><h3>${e(x.role)}</h3><p>${e(x.company)}</p></div><span>${e(x.period)}</span><p>${e(x.description)}</p></article>`).join('');}
function evidenceTable(t){return `<div class="evidence-table"><table><caption>${e(t.caption)}</caption><thead><tr>${t.headers.map(h=>`<th scope="col">${e(h)}</th>`).join('')}</tr></thead><tbody>${t.rows.map(r=>`<tr>${r.map(c=>`<td>${e(c)}</td>`).join('')}</tr>`).join('')}</tbody></table><p>${e(t.note)}</p></div>`;}
function preview(p){
if(p.id==='performance')return `<div class="proof-preview"><span class="eyebrow">보관 데이터 기준</span><strong>229<span>행</span></strong><p>키워드 분석</p><div class="mini-comparison"><span>캠페인 A · CTR <b>31.78%</b></span><span>캠페인 B · CTR <b>31.15%</b></span></div><small>2026.08 키워드 행 집계 · 개선율 아님</small></div>`;
if(p.id==='tracking')return `<div class="proof-preview tracking-preview"><span class="eyebrow">수정 코드 요약</span><div class="change-row"><b>수정 전</b><span>기존 호출 + GTM 전송 경로</span></div><div class="change-row"><b>수정 후</b><span>기존 호출 차단<br>phone_click 이벤트 유지</span></div><small>보관 코드 기준 · 현재 라이브 검증 아님</small></div>`;
return `<div class="proof-preview research-preview"><span class="eyebrow">조사 보고서 요약</span><strong>3<span>곳</span></strong><p>경쟁 치과 비교</p><div class="mini-comparison"><span>검색 가시성</span><span>일본어 랜딩</span></div><small>2026.08 · 공개 자료로 비교한 범위</small></div>`;
}
function cards(list){return `<div class="evidence-grid">${list.map(p=>`<article class="evidence-card">${preview(p)}<div class="evidence-card-body"><p class="eyebrow">${e(p.category)}</p><h3><a href="${link(p)}">${e(p.title)} ↗</a></h3><p class="project-period">${e(p.period)}</p><p><b>담당</b> ${e(p.roleShort)}</p><p><b>산출물</b> ${e(p.deliverable)}</p><a class="case-link" href="${link(p)}">사례와 근거 보기 →</a></div></article>`).join('')}</div>`;}
const funnel=`<section class="funnel-section"><div><p class="eyebrow">HOW I THINK / 02</p><h2>숫자 사이의<br>행동을 봅니다.</h2><p>단계를 선택하면, 각 지표에서 확인할 질문을 볼 수 있습니다.</p><span class="subtle">측정 구조 예시 · 실제 성과 퍼널 아님</span></div><div class="funnel"><div class="funnel-buttons" aria-label="퍼널 단계">${['Impression','Click','Session','Lead'].map((x,i)=>`<button type="button" data-stage="${i}" aria-pressed="${i===0}" style="--width:${100-i*14}%"><span>0${i+1}</span>${x}<span>↗</span></button>`).join('')}</div><div class="funnel-detail" aria-live="polite"><span id="funnel-metric">REACH & FREQUENCY</span><h3 id="funnel-title">누구에게, 얼마나 노출됐는가?</h3><p id="funnel-copy">노출 수는 도달한 사람 수와 다릅니다. 타깃과 반복 노출을 함께 확인합니다.</p></div></div></section>`;
const skills=`<div class="skill-grid">${profile.skills.map((s,i)=>`<article><span class="eyebrow">0${i+1}</span><h3>${e(s.title)}</h3><p class="tools">${e(s.tools)}</p><p>${e(s.description)}</p></article>`).join('')}</div>`;

const home=`<section class="compact-hero has-portrait"><img class="profile-portrait" src="assets/portrait.jpg" alt="박상연 증명사진" width="413" height="531"><p class="eyebrow">PERFORMANCE MARKETING PORTFOLIO</p><h1>박상연 <span>퍼포먼스 마케터</span></h1><p class="intro-line">광고를 운영하고, 데이터를 분석해 다음 개선안을 제안합니다.</p><p class="career-line">마케팅 실무 경험 <strong>2026.07–2026.09</strong><span>광고 운영 · 분석 및 보고 · 의료시장 조사</span></p><div class="hero-actions"><a class="button" href="#selected-work">대표 사례 보기 ↓</a><a class="text-link" href="resume.html">이력서 / PDF 저장 ↗</a><a class="text-link" href="mailto:${e(profile.email)}">이메일 ↗</a></div></section><section class="selected-work" id="selected-work"><div class="section-heading"><div><p class="eyebrow">직접 다룬 세 가지 실무 과제</p><h2>대표 사례</h2></div><a class="text-link" href="projects.html">기간·역할·산출물 비교 →</a></div>${cards(featured)}</section><section class="home-career"><div class="section-heading"><h2>경력 요약</h2><a class="text-link" href="about.html">일하는 방식 →</a></div>${career(profile.experience)}</section><section class="contact-strip"><div><h2>연락처 · 이력서</h2><p>${contact}</p></div><a class="button" href="resume.html">이력서 / PDF 저장 ↗</a></section>`;
await writeFile(new URL('index.html',root),layout('Home',home));
await writeFile(new URL('projects.html',root),layout('Projects',`<section class="compact-intro"><p class="eyebrow">실무 사례 / 03</p><h1>프로젝트 한눈에 보기</h1><p>기간, 담당 범위와 산출물을 비교하고 상세 근거를 확인할 수 있습니다.</p></section><section class="project-index">${projects.map((p,i)=>`<article class="project-row"><div><span class="eyebrow">0${i+1} / ${e(p.category)}</span><h2><a href="${link(p)}">${e(p.title)} ↗</a></h2><p>${e(client(p))}</p>${tags(p)}</div><dl><div><dt>기준 기간</dt><dd>${e(p.period)}</dd></div><div><dt>내 역할</dt><dd>${e(p.roleShort)}</dd></div><div><dt>산출물</dt><dd>${e(p.deliverable)}</dd></div><div><dt>확인된 결과</dt><dd>${e(p.resultShort)}</dd></div></dl><a class="case-link" href="${link(p)}">상세 사례 보기 →</a></article>`).join('')}</section>`,'Projects'));
await writeFile(new URL('about.html',root),layout('About',`<section class="page-intro about-intro"><p class="eyebrow">ABOUT / ${e(profile.englishName)}</p><h1>좋은 질문이<br>좋은 분석을 만듭니다.</h1><p>${e(profile.summary)}</p></section><section class="about-body"><div><p class="eyebrow">MY APPROACH</p><h2>숫자를 보기 전,<br>무엇을 셌는지 묻습니다.</h2></div><div class="principles"><article><span>01 / CONTEXT</span><h3>비교할 수 있는 데이터인가?</h3><p>기간, 매체, 이벤트 정의를 먼저 맞춥니다. 클릭과 상담, 예약은 각자의 의미로 읽습니다.</p></article><article><span>02 / EVIDENCE</span><h3>어디까지 확인했는가?</h3><p>진단, 제안, 실행, 검증을 구분합니다. 계정 전체 성과와 개인이 기여한 범위도 함께 설명합니다.</p></article><article><span>03 / ACTION</span><h3>다음에는 무엇을 바꿀 것인가?</h3><p>리포트를 숫자 정리로 끝내지 않고, 운영에서 검토할 우선순위와 다음 질문으로 연결합니다.</p></article></div></section><section class="skills-section"><p class="eyebrow">CAPABILITIES</p><h2>하나의 흐름으로 연결하는 역량.</h2>${skills}</section><section class="closing"><h2>실제 사례로 더 자세히.</h2><a class="button" href="projects.html">프로젝트 보기 ↗</a></section>`,'About'));

await writeFile(new URL('resume.html',root),layout('Resume',`<section class="resume-head has-portrait"><div><p class="eyebrow">이력 요약</p><h1>${e(profile.name)}<span>${e(profile.englishName)}</span></h1><p>${e(profile.role)}</p><p>${contact}</p></div><img class="profile-portrait" src="assets/portrait.jpg" alt="박상연 증명사진" width="413" height="531"><button class="button print-button" type="button" id="print-resume">인쇄 / PDF 저장 ↗</button></section><section class="resume-body"><h2>소개</h2><p>${e(profile.summary)}</p><h2>마케팅 경력</h2>${career(profile.experience.slice(0,1))}<h2>대표 사례</h2><div class="resume-projects">${featured.map(p=>`<article><h3><a href="${link(p)}">${e(p.title)} ↗</a></h3><span>${e(p.period)}</span><p>${e(p.roleShort)}</p><small>산출물: ${e(p.deliverable)}</small></article>`).join('')}</div><h2>이전 경력</h2>${career(profile.experience.slice(1))}<h2>활용 역량</h2>${skills}${profile.education.length?`<h2>학력·교육</h2>${profile.education.map(x=>`<p>${e(x)}</p>`).join('')}`:''}<aside class="evidence-note"><strong>프로젝트와 기여 범위</strong><p>광고 운영·분석·시장조사는 직접 담당했습니다. GTM 수정은 AI를 통한 실행과 검토로 구분했습니다. 소속 회사·광고주는 익명으로 표시합니다.</p></aside></section>`,'Resume'));
await mkdir(new URL('projects/',root),{recursive:true});
for(const [i,p] of projects.entries()){
const body=`<section class="compact-case"><a class="text-link" href="../projects.html">← 프로젝트 목록</a><p class="eyebrow">0${i+1} / ${e(p.category)}</p><h1>${e(p.title)}</h1><p>${e(client(p))} · ${e(p.period)}</p><p class="case-role"><b>내 역할</b> ${e(p.roleShort)}</p><div class="case-glance"><div><h2>문제</h2><p>${e(p.problemShort)}</p></div><div><h2>판단과 행동</h2><p>${e(p.decision)}</p></div><div><h2>확인된 결과</h2><p>${e(p.resultShort)}</p></div></div></section><section class="evidence-first"><div class="section-heading"><h2>작업 근거</h2><span class="eyebrow">원본 내용을 익명화·요약한 자료</span></div>${p.evidenceTable?evidenceTable(p.evidenceTable):preview(p)}<p class="evidence-boundary">${e(p.evidenceStatus)}</p></section><div class="case-layout"><aside class="case-nav"><p class="eyebrow">자세한 수행 과정</p>${Object.keys(p.sections).map((k,j)=>`<a href="#${anchor(k)}"><span>0${j+1}</span>${labels[k]}</a>`).join('')}</aside><div class="case-content">${Object.entries(p.sections).map(([k,v],j)=>`<section id="${anchor(k)}"><span class="eyebrow">0${j+1} / ${e(k)}</span><h2>${labels[k]}</h2><p>${e(v)}</p></section>`).join('')}${p.artifacts?.length?`<section class="case-artifacts"><h2>산출물</h2>${p.artifacts.map(a=>`<figure><img src="../assets/${e(a.file)}" alt="${e(a.alt)}" loading="lazy"><figcaption>${e(a.caption)}</figcaption></figure>`).join('')}</section>`:''}</div></div>${p.id==='performance'?`<details class="funnel-disclosure"><summary>분석할 때 확인하는 지표별 질문</summary>${funnel}</details>`:''}<section class="next-case"><span class="eyebrow">다음 사례</span><a href="${projects[(i+1)%projects.length].id}.html">${e(projects[(i+1)%projects.length].title)} ↗</a></section>`;
await writeFile(new URL(`projects/${p.id}.html`,root),layout(p.title,body,'Projects',1));}
await writeFile(new URL('.nojekyll',root),'');
console.log(`Built ${projects.length+4} static pages in dist/`);
